org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)

forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

mod_id=recruitsrtscommand
mod_name=Recruits RTS Command
mod_license=LGPL-3.0-only
mod_version=0.1.0-beta.1
mod_group_id=me.mss1r.recruitsrtscommand
mod_authors=mss1r
mod_description=Adds RTS group selection and map orders to the Villager Recruits tactical map.

recruits_modrinth_artifact=villager-recruits
recruits_modrinth_version=1.15.2
recruits_version_range=[1.15.2,)
